const constants = {
  INCREMENT_TREES: 'INCREMENT_TREES',
  DECREMENT_TREES: 'DECREMENT_TREES',
  FETCH_VALUE: 'FETCH_VALUE',
  FETCH_ABOUT: 'FETCH_ABOUT',
  TOGGLE_IN: 'TOGGLE_IN',
  TRACk_LIST_SUCCESS: 'TRACk_LIST_SUCCESS',
  SELECT_NOW_PLAYING: 'SELECT_NOW_PLAYING',
  ADD_TO_PLAYLIST: 'ADD_TO_PLAYLIST'
}

export default constants
